# Generated by Django 5.1.4 on 2025-01-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'verbose_name': 'My pizza recipes', 'verbose_name_plural': 'Pizza recipes'},
        ),
        migrations.AlterModelOptions(
            name='toppingsmodel',
            options={'verbose_name': 'Toppings', 'verbose_name_plural': 'Toppings'},
        ),
    ]
