# Generated by Django 5.1.4 on 2025-02-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizzamodel_options_alter_toppingsmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pizza.pizzamodel_toppings',),
        ),
    ]
