# Generated by Django 5.1.4 on 2025-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('pizza_order', models.ManyToManyField(to='pizza.pizzamodel')),
            ],
        ),
    ]
