# Generated by Django 5.1.4 on 2025-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.ordermodel_pizza_order',),
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('DEL', 'Delivered')], default='PEN', max_length=3),
        ),
    ]
